name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install QEMU
      run: |
              sudo apt update
              sudo apt install qemu-system-x86
              sudo apt install qemu-kvm
              sudo apt install qemu-utils
    - name: Switch to Nightly
      run: rustup default nightly
    - name: Add llvm-tools component
      run: rustup component add llvm-tools-preview
    - name: Add Rust Project Src
      run: rustup component add rust-src
    - name: Install Bootimage
      run: cargo install bootimage
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
